enum COLOR {
  RED = "red",
  BLACK = "black",
  WHITE = "white",
  GREED = "green",
  BLUE = "blue",
  YELLOW = "yellow",
  BLUE_CRAYOLA = "#256eff",
  SPANISH_VIOLET = "#46237a",
  MEDIUM_AQUAMARINE = "#3ddc97",
  SIZZLING_RED = "#ff495c",
  LASER_LEMON = "#ffff82",
  BEIGE = "#f5f7dc",
  GRANNY_SMITH_APPLE = "#b5d99c",
  DARK_PURPLE = "#0f0326",
  FIRE_OPAL = "#e65f5c",
  LIGHT_GOLDENROD_YELLOW = "#eef4d4",
  TEA_GREEN = "#daefb3",
  VIVID_TANGERINE = "#ea9e8d",
  ENGLISH_VERMILLION = "#d64550",
  DARK_JUNGLE_GREEN = "#1c2826",
  PLUM = "#88498f",
  CADET_BLUE = "#779fa1",
  WHEAT = "#e0cba8",
  TOMATO = "#ff6542",
}

export default COLOR;
